// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MovieWorld.EF.Models
{
    public partial class Buy
    {
        public Guid FilmId { get; set; }
        public Guid StoreId { get; set; }

        public virtual Film Film { get; set; }
        public virtual Store Store { get; set; }
    }
}