// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MovieWorld.EF.Models
{
    public partial class DeliveryPoint
    {
        public Guid Id { get; set; }
        public string Province { get; set; }
        public string Address { get; set; }
        public int Number { get; set; }
    }
}