// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MovieWorld.EF.Models
{
    public partial class Email
    {
        public string Title { get; set; }
        public string Object { get; set; }
        public string Body { get; set; }
        public string Keyword { get; set; }
        public Guid IdEmail { get; set; }
    }
}