// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MovieWorld.EF.Models
{
    public partial class FilmGenre
    {
        public Guid IdFilm { get; set; }
        public Guid IdGenre { get; set; }

        public virtual Film IdFilmNavigation { get; set; }
        public virtual Genre IdGenreNavigation { get; set; }
    }
}