// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MovieWorld.EF.Models
{
    public partial class FilmLabel
    {
        public Guid Id { get; set; }
        public string Title { get; set; }
        public string ShortPlot { get; set; }
        public Guid IdFilm { get; set; }
        public Guid IdMultilingual { get; set; }

        public virtual Multilingual IdMultilingualNavigation { get; set; }
    }
}