// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MovieWorld.EF.Models
{
    public partial class Genre
    {
        public Genre()
        {
            FilmGenre = new HashSet<FilmGenre>();
        }

        public Guid IdGenre { get; set; }
        public string Genre1 { get; set; }
        public string Color { get; set; }
        public Guid IdMultilingual { get; set; }

        public virtual ICollection<FilmGenre> FilmGenre { get; set; }
    }
}