// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MovieWorld.EF.Models
{
    public partial class Label
    {
        public Guid Id { get; set; }
        public Guid IdMultilingual { get; set; }
        public string LabelContent { get; set; }
        public string Key { get; set; }

        public virtual Multilingual IdMultilingualNavigation { get; set; }
    }
}