// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MovieWorld.EF.Models
{
    public partial class Multilingual
    {
        public Multilingual()
        {
            FilmLabel = new HashSet<FilmLabel>();
            Label = new HashSet<Label>();
            NewsLabel = new HashSet<NewsLabel>();
        }

        public Guid Id { get; set; }
        public string Language { get; set; }
        public string Img { get; set; }

        public virtual ICollection<FilmLabel> FilmLabel { get; set; }
        public virtual ICollection<Label> Label { get; set; }
        public virtual ICollection<NewsLabel> NewsLabel { get; set; }
    }
}