// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MovieWorld.EF.Models
{
    public partial class Realize
    {
        public Guid ActorMovieDirectorId { get; set; }
        public Guid FilmId { get; set; }

        public virtual Cast ActorMovieDirector { get; set; }
        public virtual Film Film { get; set; }
    }
}