// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MovieWorld.EF.Models
{
    public partial class RoleOfCast
    {
        public RoleOfCast()
        {
            Cast = new HashSet<Cast>();
        }

        public Guid Id { get; set; }
        public string Role { get; set; }

        public virtual ICollection<Cast> Cast { get; set; }
    }
}