// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MovieWorld.EF.Models
{
    public partial class Store
    {
        public Store()
        {
            Buy = new HashSet<Buy>();
        }

        public string Name { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string Cap { get; set; }
        public string Province { get; set; }
        public Guid StoreId { get; set; }

        public virtual ICollection<Buy> Buy { get; set; }
    }
}